import type { GlobalConfig } from 'payload'

export const ShippingConfig: GlobalConfig = {
  slug: 'shipping-config',
  label: 'Доставка',
  admin: {
    group: 'Налаштування',
  },
  access: {
    read: () => true,
    update: ({ req }) => req?.user?.collection === 'users',
  },
  fields: [
    {
      name: 'zones',
      label: 'Зони доставки',
      type: 'array',
      labels: { singular: 'Зона', plural: 'Зони' },
      fields: [
        {
          name: 'name',
          label: 'Назва зони',
          type: 'text',
          required: true,
          localized: true,
        },
        {
          name: 'countries',
          label: 'Країни',
          type: 'select',
          hasMany: true,
          required: true,
          options: [
            { label: 'Україна', value: 'UA' },
            { label: 'Польща', value: 'PL' },
            { label: 'Німеччина', value: 'DE' },
            { label: 'Франція', value: 'FR' },
            { label: 'Італія', value: 'IT' },
            { label: 'Іспанія', value: 'ES' },
            { label: 'Нідерланди', value: 'NL' },
            { label: 'Бельгія', value: 'BE' },
            { label: 'Австрія', value: 'AT' },
            { label: 'Чехія', value: 'CZ' },
            { label: 'Словаччина', value: 'SK' },
            { label: 'Румунія', value: 'RO' },
            { label: 'Угорщина', value: 'HU' },
            { label: 'Болгарія', value: 'BG' },
            { label: 'Хорватія', value: 'HR' },
            { label: 'Литва', value: 'LT' },
            { label: 'Латвія', value: 'LV' },
            { label: 'Естонія', value: 'EE' },
            { label: 'Швеція', value: 'SE' },
            { label: 'Данія', value: 'DK' },
            { label: 'Фінляндія', value: 'FI' },
            { label: 'Португалія', value: 'PT' },
            { label: 'Греція', value: 'GR' },
            { label: 'Великобританія', value: 'GB' },
            { label: 'Молдова', value: 'MD' },
          ],
        },
        {
          name: 'methods',
          label: 'Методи доставки',
          type: 'array',
          labels: { singular: 'Метод', plural: 'Методи' },
          fields: [
            { name: 'methodId', label: 'ID методу', type: 'text', required: true },
            { name: 'name', label: 'Назва', type: 'text', required: true, localized: true },
            {
              name: 'carrier',
              label: 'Перевізник',
              type: 'select',
              options: [
                { label: 'Нова Пошта', value: 'nova_poshta' },
                { label: 'Укрпошта', value: 'ukrposhta' },
                { label: 'DHL', value: 'dhl' },
                { label: 'DPD', value: 'dpd' },
                { label: 'GLS', value: 'gls' },
                { label: 'InPost', value: 'inpost' },
                { label: 'Poczta Polska', value: 'poczta_polska' },
                { label: 'Deutsche Post', value: 'deutsche_post' },
              ],
            },
            { name: 'price', label: 'Вартість', type: 'number', required: true, min: 0 },
            {
              name: 'currency',
              label: 'Валюта',
              type: 'select',
              defaultValue: 'UAH',
              options: [
                { label: 'UAH', value: 'UAH' },
                { label: 'EUR', value: 'EUR' },
                { label: 'PLN', value: 'PLN' },
                { label: 'USD', value: 'USD' },
              ],
            },
            { name: 'freeAbove', label: 'Безкоштовно від', type: 'number', min: 0, admin: { description: 'Безкоштовна доставка від суми' } },
            { name: 'estimatedDays', label: 'Термін доставки', type: 'text', localized: true, admin: { placeholder: '2-3 робочі дні' } },
            { name: 'isActive', label: 'Активний', type: 'checkbox', defaultValue: true },
          ],
        },
        { name: 'isActive', label: 'Активна', type: 'checkbox', defaultValue: true },
      ],
    },
    // Legacy single methods list for backward compatibility
    {
      name: 'methods',
      type: 'array',
      admin: { description: 'Застарілі методи (використовуйте зони)' },
      fields: [
        { name: 'methodId', type: 'text', required: true },
        { name: 'name', type: 'text', required: true },
        { name: 'price', type: 'number', required: true, min: 0 },
        { name: 'freeAbove', type: 'number', min: 0, admin: { description: 'Free shipping above this amount' } },
        { name: 'isActive', type: 'checkbox', defaultValue: true },
      ],
    },
  ],
}
