import type { CollectionConfig } from 'payload'

export const Promotions: CollectionConfig = {
  slug: 'promotions',
  labels: { singular: 'Промокод', plural: 'Промокоди' },
  admin: {
    useAsTitle: 'code',
    defaultColumns: ['code', 'title', 'type', 'value', 'isActive', 'usageCount', 'expiresAt'],
    group: 'Маркетинг',
  },
  access: {
    read: () => true,
    create: ({ req }) => Boolean(req?.user && req.user.collection === 'users'),
    update: ({ req }) => Boolean(req?.user && req.user.collection === 'users'),
    delete: ({ req }) => Boolean(req?.user && req.user.collection === 'users'),
  },
  fields: [
    {
      name: 'code',
      label: 'Код',
      type: 'text',
      required: true,
      unique: true,
      index: true,
      admin: { description: 'Промокод (наприклад: WELCOME10, BLACKFRIDAY)' },
      hooks: {
        beforeValidate: [({ value }) => value?.toUpperCase().trim()],
      },
    },
    { name: 'title', label: 'Назва', type: 'text', localized: true },
    { name: 'description', label: 'Опис', type: 'textarea', localized: true },
    {
      name: 'type',
      label: 'Тип знижки',
      type: 'select',
      required: true,
      options: [
        { label: 'Відсоток', value: 'percentage' },
        { label: 'Фіксована сума', value: 'fixed' },
        { label: 'Безкоштовна доставка', value: 'free_shipping' },
      ],
    },
    {
      name: 'value',
      label: 'Значення',
      type: 'number',
      required: true,
      min: 0,
      admin: { description: 'Відсоток (наприклад 10) або сума у валюті' },
    },
    {
      name: 'currency',
      label: 'Валюта (для фіксованих сум)',
      type: 'select',
      options: [
        { label: 'UAH (₴)', value: 'UAH' },
        { label: 'EUR (€)', value: 'EUR' },
        { label: 'PLN (zł)', value: 'PLN' },
        { label: 'USD ($)', value: 'USD' },
      ],
      admin: {
        condition: (_, siblingData) => siblingData?.type === 'fixed',
      },
    },
    {
      name: 'conditions',
      label: 'Умови застосування',
      type: 'group',
      fields: [
        {
          name: 'minOrderAmount',
          label: 'Мінімальна сума замовлення',
          type: 'number',
          min: 0,
        },
        {
          name: 'maxDiscountAmount',
          label: 'Максимальна знижка',
          type: 'number',
          min: 0,
          admin: { description: 'Обмеження для відсоткових знижок' },
        },
        {
          name: 'applicableCategories',
          label: 'Тільки для категорій',
          type: 'relationship',
          relationTo: 'categories',
          hasMany: true,
        },
        {
          name: 'applicableBrands',
          label: 'Тільки для брендів',
          type: 'relationship',
          relationTo: 'brands',
          hasMany: true,
        },
        {
          name: 'applicableProducts',
          label: 'Тільки для товарів',
          type: 'relationship',
          relationTo: 'products',
          hasMany: true,
        },
        {
          name: 'excludedProducts',
          label: 'Виключити товари',
          type: 'relationship',
          relationTo: 'products',
          hasMany: true,
        },
        {
          name: 'maxUsesTotal',
          label: 'Макс. використань (загалом)',
          type: 'number',
          min: 0,
          admin: { description: 'Залиште порожнім для необмежених' },
        },
        {
          name: 'maxUsesPerCustomer',
          label: 'Макс. використань на клієнта',
          type: 'number',
          min: 1,
          defaultValue: 1,
        },
      ],
    },
    {
      name: 'startsAt',
      label: 'Початок дії',
      type: 'date',
      required: true,
      admin: { date: { pickerAppearance: 'dayAndTime' } },
    },
    {
      name: 'expiresAt',
      label: 'Закінчення дії',
      type: 'date',
      required: true,
      admin: { date: { pickerAppearance: 'dayAndTime' } },
    },
    {
      name: 'isActive',
      label: 'Активний',
      type: 'checkbox',
      defaultValue: true,
      admin: { position: 'sidebar' },
    },
    {
      name: 'usageCount',
      label: 'Кількість використань',
      type: 'number',
      defaultValue: 0,
      admin: { readOnly: true, position: 'sidebar' },
    },
  ],
}
